import React, { FC } from 'react'

import { Inter } from 'next/font/google'
import Head from 'next/head'

import styles from './Home.module.scss'
import { Layout } from '@/components/layout/Layout'
import { ICar } from '@/interfaces/car.interface'
import CarItem from '@/components/ui/car/CarItem'


const inter = Inter({ subsets: ['latin'] })

export default function Home({cars}: {cars?: ICar[]} )  {
  return (
    <Layout title='Home page' description='You can find car for your life'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Cars:</h1>

      {cars?.length ? cars.map(car => <CarItem car={car} key={car.id} />) : <div>Cars not found!</div> }
    </ Layout>
  )
}
